steam:
  api-key: 3A4B7D2E3AAFBE8B4B582A00BD698B40
  base-url: https://api.steampowered.com
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/teamSteam_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: