spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/teamSteam_test
    username: lldj
    password: lldj123414
  jpa:
    hibernate:
      ddl-auto: create